package geoquestgame;

import classes.BackgroundPanel;
import classes.Premios;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gubec
 */
public class EscolhaBandeira extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    final static String[] vetorPaises = {"brasil", "chile", "argentina", "equador", "colômbia", "uruguai", "paraguai", "venezuela", "guiana", "guiana francesa", "suriname", "peru", "bolívia"};
    static List<String> paises = new ArrayList(Arrays.asList(vetorPaises));
    static List<String> paisesAuxiliar = new ArrayList(Arrays.asList(vetorPaises));
    final List<String> paisesSorteados = new ArrayList<>();
    String pais = "";
    String botao1 = "";
    String botao2 = "";
    String botao3 = "";
    String botao4 = "";
    static Integer vidas = 3;
    Premios p = new Premios();
    static boolean jaIncrementouBrasil = false;
    static boolean jaIncrementouChile = false;
    static boolean jaIncrementouArgentina = false;
    static boolean jaIncrementouEquador = false;
    static boolean jaIncrementouColombia = false;
    static boolean jaIncrementouUruguai = false;
    static boolean jaIncrementouParaguai = false;
    static boolean jaIncrementouVenezuela = false;
    static boolean jaIncrementouGuiana = false;
    static boolean jaIncrementouGuianaFrancesa = false;
    static boolean jaIncrementouSuriname = false;
    static boolean jaIncrementouPeru = false;
    static boolean jaIncrementouBolivia = false;

    public boolean isEmpty() {
        return paisesAuxiliar.isEmpty();
    }

    public EscolhaBandeira() {
        if (!paisesAuxiliar.isEmpty()) {
            Random random = new Random();

            int tamanhoLista = paises.size();
            int quantidadeStrings = 3;

            pais = paisesAuxiliar.get(random.nextInt(paisesAuxiliar.size()));
            while (paisesSorteados.size() < quantidadeStrings) {
                int indiceAleatorio = random.nextInt(tamanhoLista);
                String stringAleatoria = paises.get(indiceAleatorio);
                if (!paisesSorteados.contains(stringAleatoria) && !pais.equals(stringAleatoria)) {
                    paisesSorteados.add(stringAleatoria);
                }
            }
            
            Integer botaoCerto = random.nextInt(3);
            switch(botaoCerto) {
                case 0:
                    botao1 = pais;
                    botao2 = paisesSorteados.get(0);
                    botao3 = paisesSorteados.get(1);
                    botao4 = paisesSorteados.get(2);
                    break;
                case 1:
                    botao2 = pais;
                    botao1 = paisesSorteados.get(0);
                    botao3 = paisesSorteados.get(1);
                    botao4 = paisesSorteados.get(2);
                    break;
                case 2:
                    botao3 = pais;
                    botao2 = paisesSorteados.get(0);
                    botao1 = paisesSorteados.get(1);
                    botao4 = paisesSorteados.get(2);
                    break;
                case 3:
                    botao4 = pais;
                    botao2 = paisesSorteados.get(0);
                    botao3 = paisesSorteados.get(1);
                    botao1 = paisesSorteados.get(2);
                    break;
            }

            initComponents();
            jLabel2.setText("  " + vidas.toString());
            jLabel1.setText(pais.toUpperCase());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = jPanel1 = new BackgroundPanel(new ImageIcon(getClass().getResource("/imagens/escolhaBandeiraJogo.png")).getImage());
        jButton1 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/"+botao1+".png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jButton2 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/Group 5.png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jButton3 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/"+botao2+".png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jButton4 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/"+botao4+".png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jButton5 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/"+botao3+".png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAIS");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vida.png"))); // NOI18N
        jLabel2.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jogo(botao1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Jogos j = new Jogos();
        j.setLocationRelativeTo(null);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jogo(botao4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jogo(botao2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jogo(botao3);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jogo(final String botao) {
        if (pais.equalsIgnoreCase(botao)) {
            paisesAuxiliar.remove(pais);
            JOptionPane.showMessageDialog(rootPane, "Parabéns você acertou!", "Sucesso", 1);
            Jogos.porcentagemJogo2 += 7.7;
            premiosPaises(pais);
            Jogos j = new Jogos();
            j.setLocationRelativeTo(null);
            j.setVisible(true);
            this.dispose();
        } else {
            if (vidas == 1) {
                paisesAuxiliar = new ArrayList();
                paisesAuxiliar.addAll(Arrays.asList(vetorPaises));
                Jogos.porcentagemJogo2 = 0;
                Jogos j = new Jogos();
                vidas = 3;
                JOptionPane.showMessageDialog(rootPane, "Você perdeu sua win streak, comece novamente!", "Erro", 0);
                j.setLocationRelativeTo(null);
                j.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você errou!", "Erro", 0);
                vidas--;
                jLabel2.setText("  " + vidas.toString());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaBandeira().setVisible(true);
            }
        });
    }
    
    private void premiosPaises(final String paisPremio) {
        switch (paisPremio.toLowerCase()) {
            case "brasil":
                p.premios(paisPremio, jaIncrementouBrasil);
                jaIncrementouBrasil = true;
                if(Premios.premioBrasil == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Brasil, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "chile":
                p.premios(paisPremio, jaIncrementouChile);
                jaIncrementouChile = true;
                if(Premios.premioChile == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Chile, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "argentina":
                p.premios(paisPremio, jaIncrementouArgentina);
                jaIncrementouArgentina = true;
                if(Premios.premioArgentina == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Argentina, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "equador":
                p.premios(paisPremio, jaIncrementouEquador);
                jaIncrementouEquador = true;
                if(Premios.premioEquador == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Equador, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "colômbia":
                p.premios(paisPremio, jaIncrementouColombia);
                jaIncrementouColombia = true;
                if(Premios.premioColombia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Colômbia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "uruguai":
                p.premios(paisPremio, jaIncrementouUruguai);
                jaIncrementouUruguai = true;
                if(Premios.premioUruguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Uruguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "paraguai":
                p.premios(paisPremio, jaIncrementouParaguai);
                jaIncrementouParaguai = true;
                if(Premios.premioParaguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Paraguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "venezuela":
                p.premios(paisPremio, jaIncrementouVenezuela);
                jaIncrementouVenezuela = true;
                if(Premios.premioVenezuela == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Venezuela, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana":
                p.premios(paisPremio, jaIncrementouGuiana);
                jaIncrementouGuiana = true;
                if(Premios.premioGuiana == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana francesa":
                p.premios(paisPremio, jaIncrementouGuianaFrancesa);
                jaIncrementouGuianaFrancesa = true;
                if(Premios.premioGuianaFrancesa == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana Francesa, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "suriname":
                p.premios(paisPremio, jaIncrementouSuriname);
                jaIncrementouSuriname = true;
                if(Premios.premioSuriname == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Suriname, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "peru":
                p.premios(paisPremio, jaIncrementouPeru);
                jaIncrementouPeru = true;
                if(Premios.premioPeru == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Peru, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "bolívia":
                p.premios(paisPremio, jaIncrementouBolivia);
                jaIncrementouBolivia = true;
                if(Premios.premioBolivia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Bolívia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
