/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geoquestgame;

import classes.BackgroundPanel;
import classes.Premios;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CIANDT\gustavofb
 */
public class MapaMundi extends javax.swing.JFrame {

    final static String[] vetorPaises = {"brasil", "chile", "argentina", "equador", "colômbia", "uruguai", "paraguai", "venezuela", "guiana", "guiana francesa", "suriname", "peru", "bolívia"};
    static List<String> paises = new ArrayList(Arrays.asList(vetorPaises));
    static List<String> paisesAuxiliar = new ArrayList(Arrays.asList(vetorPaises));
    final List<String> paisesSorteados = new ArrayList<>();
    Random random = new Random();
    String pais = "";
    static Integer vidas = 3;
    Premios p = new Premios();
    static boolean jaIncrementouBrasil = false;
    static boolean jaIncrementouChile = false;
    static boolean jaIncrementouArgentina = false;
    static boolean jaIncrementouEquador = false;
    static boolean jaIncrementouColombia = false;
    static boolean jaIncrementouUruguai = false;
    static boolean jaIncrementouParaguai = false;
    static boolean jaIncrementouVenezuela = false;
    static boolean jaIncrementouGuiana = false;
    static boolean jaIncrementouGuianaFrancesa = false;
    static boolean jaIncrementouSuriname = false;
    static boolean jaIncrementouPeru = false;
    static boolean jaIncrementouBolivia = false;

    public boolean isEmpty() {
        return paisesAuxiliar.isEmpty();
    }

    /**
     * Creates new form QualBandeiraBrasil
     */
    public MapaMundi() {
        if (!paisesAuxiliar.isEmpty()) {
            pais = paisesAuxiliar.get(random.nextInt(paisesAuxiliar.size()));
            initComponents();
            jLabel2.setText("  " + vidas.toString());

            while (paisesSorteados.size() < 3) {
                int indiceAleatorio = random.nextInt(paises.size());
                String stringAleatoria = paises.get(indiceAleatorio);
                if (!paisesSorteados.contains(stringAleatoria) && !pais.equals(stringAleatoria)) {
                    paisesSorteados.add(stringAleatoria);
                }
            }
            Integer botaoCerto = random.nextInt(3);
            switch (botaoCerto) {
                case 0:
                    jButton2.setText(pais.toUpperCase());
                    jButton3.setText(paisesSorteados.get(0).toUpperCase());
                    jButton4.setText(paisesSorteados.get(1).toUpperCase());
                    jButton5.setText(paisesSorteados.get(2).toUpperCase());
                    break;
                case 1:
                    jButton3.setText(pais.toUpperCase());
                    jButton2.setText(paisesSorteados.get(0).toUpperCase());
                    jButton4.setText(paisesSorteados.get(1).toUpperCase());
                    jButton5.setText(paisesSorteados.get(2).toUpperCase());
                    break;
                case 2:
                    jButton4.setText(pais.toUpperCase());
                    jButton3.setText(paisesSorteados.get(0).toUpperCase());
                    jButton2.setText(paisesSorteados.get(1).toUpperCase());
                    jButton5.setText(paisesSorteados.get(2).toUpperCase());
                    break;
                case 3:
                    jButton5.setText(pais.toUpperCase());
                    jButton3.setText(paisesSorteados.get(0).toUpperCase());
                    jButton4.setText(paisesSorteados.get(1).toUpperCase());
                    jButton2.setText(paisesSorteados.get(2).toUpperCase());
                    break;
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = jPanel1 = new BackgroundPanel(new ImageIcon(getClass().getResource("/imagens/qualNomeDaBandeira.png")).getImage());
        jPanel2 = new BackgroundPanel(new ImageIcon(getClass().getResource("/imagens/"+pais+"Mapa.jpg")).getImage());
        jButton1 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/Group 5.png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vida.png"))); // NOI18N
        jLabel2.setText("  3");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(153, 153, 153))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Jogos j = new Jogos();
        j.setLocationRelativeTo(null);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jogo(jButton4.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jogo(jButton2.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jogo(jButton3.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jogo(jButton5.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jogo(final String botao) {
        if (pais.equalsIgnoreCase(botao)) {
            paisesAuxiliar.remove(botao.toLowerCase());
            JOptionPane.showMessageDialog(rootPane, "Parabéns você acertou!", "Sucesso", 1);
            Jogos.porcentagemJogo3 += 7.7;
            premiosPaises(pais);
            Jogos j = new Jogos();
            j.setLocationRelativeTo(null);
            j.setVisible(true);
            this.dispose();
        } else {
            if (vidas == 1) {
                paisesAuxiliar = new ArrayList();
                paisesAuxiliar.addAll(Arrays.asList(vetorPaises));
                Jogos.porcentagemJogo3 = 0;
                Jogos j = new Jogos();
                vidas = 3;
                JOptionPane.showMessageDialog(rootPane, "Você perdeu sua win streak, comece novamente!", "Erro", 0);
                j.setLocationRelativeTo(null);
                j.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você errou!", "Erro", 0);
                vidas--;
                jLabel2.setText("  " + vidas.toString());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaMundi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaMundi().setVisible(true);
            }
        });
    }

    private void premiosPaises(final String paisPremio) {
        switch (paisPremio.toLowerCase()) {
            case "brasil":
                p.premios(paisPremio, jaIncrementouBrasil);
                jaIncrementouBrasil = true;
                if(Premios.premioBrasil == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Brasil, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "chile":
                p.premios(paisPremio, jaIncrementouChile);
                jaIncrementouChile = true;
                if(Premios.premioChile == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Chile, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "argentina":
                p.premios(paisPremio, jaIncrementouArgentina);
                jaIncrementouArgentina = true;
                if(Premios.premioArgentina == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Argentina, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "equador":
                p.premios(paisPremio, jaIncrementouEquador);
                jaIncrementouEquador = true;
                if(Premios.premioEquador == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Equador, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "colômbia":
                p.premios(paisPremio, jaIncrementouColombia);
                jaIncrementouColombia = true;
                if(Premios.premioColombia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Colômbia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "uruguai":
                p.premios(paisPremio, jaIncrementouUruguai);
                jaIncrementouUruguai = true;
                if(Premios.premioUruguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Uruguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "paraguai":
                p.premios(paisPremio, jaIncrementouParaguai);
                jaIncrementouParaguai = true;
                if(Premios.premioParaguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Paraguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "venezuela":
                p.premios(paisPremio, jaIncrementouVenezuela);
                jaIncrementouVenezuela = true;
                if(Premios.premioVenezuela == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Venezuela, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana":
                p.premios(paisPremio, jaIncrementouGuiana);
                jaIncrementouGuiana = true;
                if(Premios.premioGuiana == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana francesa":
                p.premios(paisPremio, jaIncrementouGuianaFrancesa);
                jaIncrementouGuianaFrancesa = true;
                if(Premios.premioGuianaFrancesa == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana Francesa, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "suriname":
                p.premios(paisPremio, jaIncrementouSuriname);
                jaIncrementouSuriname = true;
                if(Premios.premioSuriname == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Suriname, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "peru":
                p.premios(paisPremio, jaIncrementouPeru);
                jaIncrementouPeru = true;
                if(Premios.premioPeru == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Peru, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "bolívia":
                p.premios(paisPremio, jaIncrementouBolivia);
                jaIncrementouBolivia = true;
                if(Premios.premioBolivia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Bolívia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
