/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geoquestgame;

import classes.BackgroundPanel;
import classes.Premios;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CIANDT\gustavofb
 */
public class QualBandeira extends javax.swing.JFrame {

    final static String[] vetorPaises = {"brasil", "chile", "argentina", "equador", "colômbia", "uruguai", "paraguai", "venezuela", "guiana", "guiana francesa", "suriname", "peru", "bolívia"};
    static List<String> paises = new ArrayList(Arrays.asList(vetorPaises));
    Random random = new Random();
    String pais = "";
    static Integer vidas = 3;
    Premios p = new Premios();
    static boolean jaIncrementouBrasil = false;
    static boolean jaIncrementouChile = false;
    static boolean jaIncrementouArgentina = false;
    static boolean jaIncrementouEquador = false;
    static boolean jaIncrementouColombia = false;
    static boolean jaIncrementouUruguai = false;
    static boolean jaIncrementouParaguai = false;
    static boolean jaIncrementouVenezuela = false;
    static boolean jaIncrementouGuiana = false;
    static boolean jaIncrementouGuianaFrancesa = false;
    static boolean jaIncrementouSuriname = false;
    static boolean jaIncrementouPeru = false;
    static boolean jaIncrementouBolivia = false;

    public boolean isEmpty() {
        return paises.isEmpty();
    }

    /**
     * Creates new form QualBandeiraBrasil
     */
    public QualBandeira() {
        if (!paises.isEmpty()) {
            pais = paises.get(random.nextInt(paises.size()));
            initComponents();
            jLabel2.setText("  " + vidas.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = jPanel1 = new BackgroundPanel(new ImageIcon(getClass().getResource("/imagens/qualNomeDaBandeira.png")).getImage());
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new BackgroundPanel(new ImageIcon(getClass().getResource("/imagens/"+pais+".png")).getImage());
        jButton1 = new javax.swing.JButton() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagens/Group 5.png")).getImage();
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.drawImage(img, 0, 0, getWidth(), getHeight(), null);
                g2.dispose();
            }
        };
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vida.png"))); // NOI18N
        jLabel2.setText("  3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (pais.equalsIgnoreCase(jTextField1.getText().trim())) {
                paises.remove(pais);
                JOptionPane.showMessageDialog(rootPane, "Parabéns você acertou!", "Sucesso", 1);
                Jogos.porcentagemJogo1 += 7.7;
                premiosPaises(pais);
                Jogos j = new Jogos();
                j.setLocationRelativeTo(null);
                j.setVisible(true);
                this.dispose();
            } else {
                if (vidas == 1) {
                    paises = new ArrayList();
                    paises.addAll(Arrays.asList(vetorPaises));
                    vidas = 3;
                    Jogos.porcentagemJogo1 = 0;
                    Jogos j = new Jogos();
                    JOptionPane.showMessageDialog(rootPane, "Você perdeu sua win streak, comece novamente!", "Erro", 0);
                    j.setLocationRelativeTo(null);
                    j.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Você errou!", "Erro", 0);
                    vidas--;
                    jLabel2.setText("  " + vidas.toString());
                    jTextField1.setText("");
                }
            }

        }
    }//GEN-LAST:event_jTextField1KeyPressed

    
    private void premiosPaises(final String paisPremio) {
        switch (paisPremio.toLowerCase()) {
            case "brasil":
                p.premios(paisPremio, jaIncrementouBrasil);
                jaIncrementouBrasil = true;
                if(Premios.premioBrasil == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Brasil, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "chile":
                p.premios(paisPremio, jaIncrementouChile);
                jaIncrementouChile = true;
                if(Premios.premioChile == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Chile, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "argentina":
                p.premios(paisPremio, jaIncrementouArgentina);
                jaIncrementouArgentina = true;
                if(Premios.premioArgentina == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Argentina, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "equador":
                p.premios(paisPremio, jaIncrementouEquador);
                jaIncrementouEquador = true;
                if(Premios.premioEquador == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Equador, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "colômbia":
                p.premios(paisPremio, jaIncrementouColombia);
                jaIncrementouColombia = true;
                if(Premios.premioColombia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Colômbia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "uruguai":
                p.premios(paisPremio, jaIncrementouUruguai);
                jaIncrementouUruguai = true;
                if(Premios.premioUruguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Uruguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "paraguai":
                p.premios(paisPremio, jaIncrementouParaguai);
                jaIncrementouParaguai = true;
                if(Premios.premioParaguai == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Paraguai, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "venezuela":
                p.premios(paisPremio, jaIncrementouVenezuela);
                jaIncrementouVenezuela = true;
                if(Premios.premioVenezuela == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Venezuela, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana":
                p.premios(paisPremio, jaIncrementouGuiana);
                jaIncrementouGuiana = true;
                if(Premios.premioGuiana == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "guiana francesa":
                p.premios(paisPremio, jaIncrementouGuianaFrancesa);
                jaIncrementouGuianaFrancesa = true;
                if(Premios.premioGuianaFrancesa == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Guiana Francesa, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "suriname":
                p.premios(paisPremio, jaIncrementouSuriname);
                jaIncrementouSuriname = true;
                if(Premios.premioSuriname == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Suriname, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "peru":
                p.premios(paisPremio, jaIncrementouPeru);
                jaIncrementouPeru = true;
                if(Premios.premioPeru == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio do Peru, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
            case "bolívia":
                p.premios(paisPremio, jaIncrementouBolivia);
                jaIncrementouBolivia = true;
                if(Premios.premioBolivia == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou um prêmio da Bolívia, entre na aba de Coleção para vê-lo!", "Sucesso", 1);
                }
                break;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Jogos j = new Jogos();
        j.setLocationRelativeTo(null);
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QualBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QualBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QualBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QualBandeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QualBandeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
